services:
  - type: static
    name: ev-priority-website
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDirectory: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache

